# copy()

In [1]:
import numpy as np

In [5]:
m = np.random.randint(0,10, size=(5, 5))

In [6]:
m

array([[6, 1, 2, 6, 1],
       [2, 7, 0, 1, 5],
       [6, 2, 8, 2, 0],
       [7, 1, 6, 5, 4],
       [2, 0, 3, 4, 7]])

In [7]:
alt_a = m[0:3, 0:3]

In [8]:
alt_a

array([[6, 1, 2],
       [2, 7, 0],
       [6, 2, 8]])

In [18]:
alt_a[0,0] = 33

In [11]:
alt_a

array([[33,  1,  2],
       [ 2,  7,  0],
       [ 6,  2,  8]])

In [12]:
m

array([[33,  1,  2,  6,  1],
       [ 2,  7,  0,  1,  5],
       [ 6,  2,  8,  2,  0],
       [ 7,  1,  6,  5,  4],
       [ 2,  0,  3,  4,  7]])

In [19]:
alt_b = m[0:3, 0:3].copy()

In [20]:
alt_b

array([[33,  1,  2],
       [ 2,  7,  0],
       [ 6,  2,  8]])

In [21]:
alt_b[0,0] = 66

In [22]:
alt_b

array([[66,  1,  2],
       [ 2,  7,  0],
       [ 6,  2,  8]])

In [23]:
alt_a

array([[33,  1,  2],
       [ 2,  7,  0],
       [ 6,  2,  8]])

In [24]:
m

array([[33,  1,  2,  6,  1],
       [ 2,  7,  0,  1,  5],
       [ 6,  2,  8,  2,  0],
       [ 7,  1,  6,  5,  4],
       [ 2,  0,  3,  4,  7]])