# Fancy index ile elemanlara erişmek

In [3]:
import numpy as np

In [39]:
v = np.arange(0, 30, 3)

In [51]:
v

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [25]:
v[1]

3

In [26]:
v[3]

9

In [27]:
v[-1]

27

In [1]:
getir = [1, 3, -1]

In [41]:
v[getir]

array([ 3,  9, 27])

Bu şekilde bir filtreleme işlemi yapmış olduk.

In [48]:
v

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [54]:
m = np.arange(0, 9).reshape(3, 3)

In [56]:
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [58]:
m[0:2, [0, 2]]

array([[0, 2],
       [3, 5]])

In [59]:
m[[0,2], :3]

array([[0, 1, 2],
       [6, 7, 8]])