# Slice

1:3 | 1 slice 3 | 1' den 3' e kadar git.

In [2]:
import numpy as np

In [5]:
matris = np.arange(9).reshape(3,3)

In [6]:
matris

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [50]:
matris[0,0]

0

In [51]:
matris[0:3]

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [57]:
matris[[0, 2],0:2]

array([[0, 1],
       [6, 7]])

In [59]:
matris[:1, 0:2]

array([[0, 1]])

In [63]:
matris[0:3:2]

array([[0, 1, 2],
       [6, 7, 8]])

**_______________________________________________________________________________________________________________**

In [13]:
matris[0, 0]

0

tek boyutlu bir array için: matris[index] = satırları seçer

**_______________________________________________________________________________________________________________**

In [20]:
matris

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [15]:
matris[2]

array([6, 7, 8])

matris[index1, index2] = elemanları seçer

**_______________________________________________________________________________________________________________**

In [21]:
matris

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [70]:
matris[[0, 2],[1,2]] # listelerden alınan satır ve sütun indexleri elemanları seçiyor

array([1, 8])

matris[ [index1, index2] , [index3, index4] ] = [i1, i2] --> satır indexleri  | [i3, i4] --> sütun indexleri

**_______________________________________________________________________________________________________________**

In [71]:
matris

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [82]:
matris[1:3, 1:3]

array([[4, 5],
       [7, 8]])

matris[i1:i2, i3:i4] ==> i1:i2 ile satır aralığını i3:i4 ile sütun aralığını belirterek mevcut arrayin bir alt kümesi oluşturuldu.

**_______________________________________________________________________________________________________________**

In [83]:
matris

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [86]:
matris[matris > 4]

array([5, 6, 7, 8])

------- Filtreledik hocam oyee -------

**_______________________________________________________________________________________________________________**