# İNDEX İLE ARRAY ELEMANLARINA ERİŞMEK

In [1]:
import numpy as np

**_______________________________________________________________________________________________________________**

In [12]:
a = np.arange(9)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

Tek boyutlu bir array oluşturuldu.

**_______________________________________________________________________________________________________________**

In [14]:
a[0], a[-1], a[4]

(0, 8, 4)

Tek boyutlu arraylerde belirli bir indexin elemanına erişirken listelerde yaptığımız gibi '[ ]' parantezler içine elemanın indeksini girebiliriz.

**_______________________________________________________________________________________________________________**

In [15]:
a[0] = 9

In [16]:
a

array([9, 1, 2, 3, 4, 5, 6, 7, 8])

Girilen index'e '9' değerini atadık.

**_______________________________________________________________________________________________________________**

In [24]:
b = np.random.randint(10, size=(3,3))

In [25]:
b

array([[9, 4, 3],
       [6, 1, 0],
       [5, 1, 1]])

İki boyutlu bir array oluşturuldu.

**_______________________________________________________________________________________________________________**

In [28]:
b[0,0], b[0,1], b[1,2]

(9, 4, 0)

In [29]:
b[0,0] = 10

In [30]:
b

array([[10,  4,  3],
       [ 6,  1,  0],
       [ 5,  1,  1]])

Belirli bir indexteki elemana erişme işlemlerimiz tek boyutta yaptığımızdan pek farklı değil. b arrayi a arrayinden 1 boyut daha fazla olduğu için b arrayinde bulunan bir elemanın ikinci bir index değeri daha vardır. Bu yüzden işlemlerimize ikinci index değerinide katıyoruz.

**_______________________________________________________________________________________________________________**

**Peki ya dtype=int olan bir arraye type' ı farklı olan bir değer eklersek ne olur?**

In [31]:
b

array([[10,  4,  3],
       [ 6,  1,  0],
       [ 5,  1,  1]])

In [54]:
b.dtype

dtype('int32')

In [47]:
b[0,0] = 3.14

In [45]:
b

array([[3, 4, 3],
       [6, 1, 0],
       [5, 1, 1]])

In [48]:
b.dtype

dtype('int32')

Yani eğer belirli arrayin belirli bir indeksinin değerini arrayin 'dtype' dan farklı bir değere eşitlerseniz: arrayin 'dtype' ına göre type dönüşümü gerçekleşir uygun bir type dönüşümü gerçekleşmiyorsa tahmin edebileceğiniz gibi hata alırsınız.

In [49]:
b

array([[3, 4, 3],
       [6, 1, 0],
       [5, 1, 1]])

Örnek 1

In [50]:
b[0,0] = '4'

In [51]:
b

array([[4, 4, 3],
       [6, 1, 0],
       [5, 1, 1]])

'4' değeri string iken. arraye yerleştirildiğinde bu arrayin dtype=int olduğundan ( string  > > >  int ) type dönüşümü gerçekleşir.

Örnek 2

In [61]:
b[0,0] = 'T'

ValueError: invalid literal for int() with base 10: 'T'

**_______________________________________________________________________________________________________________**

'T' stringinin type dönüşümü gerçekleşemedi. Çünkü bu string uygun formatta değildir. Bir stringin int' e type dönüşümü gerçekleştirilebilmesi için stringin str(int()) formatında olması gerekir.