# Numpy ile iki bilinmeyenli denklem çözümü

In [1]:
import numpy as np

5 * x0 + x1 = 12
x0 + 3 * x1 =0 10

In [27]:
a = np.array([[5,1], [1,3]])
b = np.array([12,10])

In [28]:
a

array([[5, 1],
       [1, 3]])

In [29]:
b

array([12, 10])

In [30]:
x = np.linalg.solve(a, b)

In [31]:
x

array([1.85714286, 2.71428571])