# MATEMATİKSEL İŞLEMLER

In [2]:
import numpy as np

In [3]:
a = np.arange(1, 10).reshape(3, 3)

In [4]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
a * 5

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [6]:
a + 5

array([[ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [7]:
a - 1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [8]:
a / 0.5

array([[ 2.,  4.,  6.],
       [ 8., 10., 12.],
       [14., 16., 18.]])

In [9]:
a % 2

array([[1, 0, 1],
       [0, 1, 0],
       [1, 0, 1]], dtype=int32)

In [16]:
np.power(a, 2)

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]], dtype=int32)

In [11]:
np.sin(180)

-0.8011526357338304

In [13]:
np.sin(a)

array([[ 0.84147098,  0.90929743,  0.14112001],
       [-0.7568025 , -0.95892427, -0.2794155 ],
       [ 0.6569866 ,  0.98935825,  0.41211849]])