# Array Sıralama (Sorting)

In [1]:
import numpy as np

**TEK BOYULAR İÇİN**

In [2]:
v = np.array([2, 1, 4, 3, 5])

In [3]:
v

array([2, 1, 4, 3, 5])

In [8]:
np.sort(v)

array([1, 2, 3, 4, 5])

In [5]:
v # Yapılan sıralama işlemi v arrayini değiştirmedi

array([2, 1, 4, 3, 5])

**__________________________________________________________________________________________**

**' sort() ' fonksiyonunu  ' .sort() ' metodu olarak kullanılırsa yapılan sıralama işlemi arrayin yapısını kalıcı şekilde değiştir.**

In [14]:
v.sort()

In [7]:
v

array([1, 2, 3, 4, 5])

## İKİ BOYUTLU ARRAY SIRALAMA

In [10]:
m = np.random.normal(20, 5, (3, 3)) # Ortalaması 20, standart sapması 5 olan 3'e 3'lük bir matris oluşturuldu.

In [11]:
m

array([[25.86218195, 26.55427329, 16.01354503],
       [13.69933436, 17.15739926, 25.14689397],
       [15.70509435, 16.96175188, 21.94310471]])

In [12]:
np.sort(m, axis=1)

array([[16.01354503, 25.86218195, 26.55427329],
       [13.69933436, 17.15739926, 25.14689397],
       [15.70509435, 16.96175188, 21.94310471]])

In [13]:
np.sort(m, axis=0)

array([[13.69933436, 16.96175188, 16.01354503],
       [15.70509435, 17.15739926, 21.94310471],
       [25.86218195, 26.55427329, 25.14689397]])