In [1]:
import numpy as np

In [2]:
arr1 = np.arange(1,10).reshape(3, 3)
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [3]:
arr1 > 3

array([[False, False, False],
       [ True,  True,  True],
       [ True,  True,  True]])

In [4]:
arr1[arr1 > 3]

array([4, 5, 6, 7, 8, 9])

In [6]:
arr2 = np.arange(9, 0, -1).reshape(3, 3)
arr2

array([[9, 8, 7],
       [6, 5, 4],
       [3, 2, 1]])

**_____________________________________________________________________________________________**

In [7]:
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
arr2

array([[9, 8, 7],
       [6, 5, 4],
       [3, 2, 1]])

**_____________________________________________________________________________________________**

In [11]:
arr1[arr2]

IndexError: index 9 is out of bounds for axis 0 with size 3

In [12]:
arr2 > 3

array([[ True,  True,  True],
       [ True,  True,  True],
       [False, False, False]])

In [13]:
arr1[arr2 > 3]

array([1, 2, 3, 4, 5, 6])

**_____________________________________________________________________________________________**

In [20]:
arr1[2]

array([7, 8, 9])

In [23]:
arr1[2].shape

(3,)

In [25]:
arr1[2].ndim

1

**____________________________________________________________________________**

In [21]:
arr1[[2]]

array([[7, 8, 9]])

In [24]:
arr1[[2]].shape

(1, 3)

In [26]:
arr1[[2]].ndim

2