In [61]:
import numpy as np

In [66]:
array1 = np.random.randint(0, 10, (3, 3))

In [70]:
array1.shape

(3, 3)

In [71]:
array1.dtype

dtype('int32')

In [72]:
array1.size

9

In [73]:
array1.ndim

2

In [74]:
array1.reshape(1, 9)

array([[9, 3, 3, 7, 3, 3, 7, 0, 2]])

In [75]:
array1

array([[9, 3, 3],
       [7, 3, 3],
       [7, 0, 2]])

In [93]:
array1.sort()

In [94]:
array1

array([[6, 8, 9],
       [2, 6, 8],
       [6, 7, 7]])

In [102]:
array1 = np.random.randint(0, 10, (3, 3))

In [92]:
array1

array([[9, 6, 8],
       [8, 6, 2],
       [6, 7, 7]])

In [96]:
array1 = array1.reshape(1, 9)

In [97]:
array1.sort()

In [98]:
array1

array([[2, 6, 6, 6, 7, 7, 8, 8, 9]])

In [100]:
array1 = array1.reshape(3, 3)

In [101]:
array1

array([[2, 6, 6],
       [6, 7, 7],
       [8, 8, 9]])

In [115]:
array1 = np.random.randint(0, 10, (3, 3))

In [116]:
array1

array([[9, 0, 7],
       [5, 9, 1],
       [7, 7, 5]])

In [105]:
array1.sort(axis=1)

In [106]:
array1

array([[3, 3, 4],
       [0, 3, 5],
       [1, 1, 4]])

In [107]:
array1.sort(axis=0)

In [108]:
array1

array([[0, 1, 4],
       [1, 3, 4],
       [3, 3, 5]])

In [109]:
array1

array([[0, 1, 4],
       [1, 3, 4],
       [3, 3, 5]])

In [121]:
array1 = np.random.randint(0, 9, (3, 3))

In [122]:
array1

array([[0, 7, 4],
       [4, 3, 4],
       [5, 2, 6]])

In [125]:
array1 = array1.sort(axis=1)

In [127]:
array1

In [129]:
np.zeros((3, 3), dtype=int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [130]:
np.ones((3, 3), dtype=int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [131]:
np.full((3, 3), 3)

array([[3, 3, 3],
       [3, 3, 3],
       [3, 3, 3]])

In [134]:
np.linspace(0, 10, 11)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [135]:
np.random.normal(10, 5, (3, 3))

array([[14.38504608,  7.57064125,  5.06119485],
       [18.11076152, 14.64884683,  8.09969581],
       [ 5.76220841,  4.30738246, 19.84052414]])

In [136]:
np.random.rand(1, 9)

array([[0.23009678, 0.08195458, 0.6774611 , 0.91499621, 0.91638154,
        0.45495304, 0.25304104, 0.32049356, 0.91684654]])

In [137]:
np.random.randn(1, 9)

array([[-1.22482767, -0.01127071,  1.18920345, -0.4828105 ,  0.89556553,
        -1.46692288, -0.46873497, -2.3860949 , -1.54876174]])

In [138]:
np.random.randint(1, 9, (1, 9))

array([[1, 4, 8, 3, 1, 6, 7, 8, 1]])

In [144]:
np.arange(1, 10).reshape(3, 3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [146]:
a = np.random.randint(0, 9, (3, 3))

In [147]:
b = np.random.randint(0, 9, (3, 3))

In [148]:
a, b

(array([[6, 6, 5],
        [3, 1, 4],
        [6, 0, 0]]),
 array([[1, 7, 2],
        [7, 0, 7],
        [2, 7, 0]]))

In [150]:
np.concatenate([a, b])

array([[6, 6, 5],
       [3, 1, 4],
       [6, 0, 0],
       [1, 7, 2],
       [7, 0, 7],
       [2, 7, 0]])

In [151]:
np.concatenate([a, b], axis=1)

array([[6, 6, 5, 1, 7, 2],
       [3, 1, 4, 7, 0, 7],
       [6, 0, 0, 2, 7, 0]])

In [152]:
np.concatenate([b, a], axis=1)

array([[1, 7, 2, 6, 6, 5],
       [7, 0, 7, 3, 1, 4],
       [2, 7, 0, 6, 0, 0]])

In [159]:
np.concatenate([np.array([1, 2, 3]).reshape(1, 3), np.array([4, 5, 6]).reshape(1, 3)], axis=0)

array([[1, 2, 3],
       [4, 5, 6]])

In [162]:
array2 = np.random.randint(0, 9, (4, 4))

In [163]:
array2

array([[7, 5, 1, 7],
       [2, 6, 5, 5],
       [4, 8, 8, 3],
       [1, 6, 8, 1]])

In [168]:
np.vsplit(array2, 2)

[array([[7, 5, 1, 7],
        [2, 6, 5, 5]]),
 array([[4, 8, 8, 3],
        [1, 6, 8, 1]])]

In [169]:
np.hsplit(array2, 2)

[array([[7, 5],
        [2, 6],
        [4, 8],
        [1, 6]]),
 array([[1, 7],
        [5, 5],
        [8, 3],
        [8, 1]])]

In [170]:
lineer_array = np.arange(1, 9)

In [171]:
lineer_array

array([1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
lineer_array.sp