# Koşullu Eleman İşlemleri

In [1]:
import numpy as np
import pandas as pd

In [2]:
data = np.random.randint(0, 10, (3,3))

In [12]:
df = pd.DataFrame(data, index=['A', 'B', 'C'], columns=['column1', 'column2', 'column3'])
df

column1  column2  column3
A        6        5        1
B        1        8        7
C        1        5        4

**________________________________________________________________________________________________**

In [6]:
arr1 = np.random.randint(0, 10, (3, 3))
arr1

array([[1, 5, 4],
       [2, 6, 7],
       [2, 6, 0]])

In [7]:
arr1[0]

array([1, 5, 4])

In [11]:
arr1[:3, [2]]

array([[4],
       [7],
       [0]])

**________________________________________________________________________________________________**

In [13]:
df

column1  column2  column3
A        6        5        1
B        1        8        7
C        1        5        4

In [15]:
df.iloc[0]

column1    6
column2    5
column3    1
Name: A, dtype: int32

In [ ]:
df['A'] # Hata verir!

In [17]:
df['column1']

A    6
B    1
C    1
Name: column1, dtype: int32

In [18]:
df.loc['A']

column1    6
column2    5
column3    1
Name: A, dtype: int32

**________________________________________________________________________________________________**

In [19]:
df[0:2]

column1  column2  column3
A        6        5        1
B        1        8        7

In [28]:
df[0:2][:1][['column1', 'column2']]

column1  column2
A        6        5

In [33]:
df

column1  column2  column3
A        6        5        1
B        1        8        7
C        1        5        4

In [34]:
df[0:2]

column1  column2  column3
A        6        5        1
B        1        8        7

In [38]:
df['column3']

A    1
B    7
C    4
Name: column3, dtype: int32

In [39]:
df[['column3']]

column3
A        1
B        7
C        4

In [40]:
df[['column1', 'column3']]

column1  column3
A        6        1
B        1        7
C        1        4

In [60]:
df.loc['A':'B', 'column1':'column3']

column1  column2  column3
A        6        5        1
B        1        8        7

In [61]:
df['A':'B']

column1  column2  column3
A        6        5        1
B        1        8        7

In [62]:
df.loc['A':'B']

column1  column2  column3
A        6        5        1
B        1        8        7

In [63]:
df.loc['A':'B', 'column1':'column2']

column1  column2
A        6        5
B        1        8

In [64]:
df['A':'B']

column1  column2  column3
A        6        5        1
B        1        8        7

In [66]:
df['A':'B']

column1  column2  column3
A        6        5        1
B        1        8        7

In [67]:
df['column1']

A    6
B    1
C    1
Name: column1, dtype: int32

In [75]:
df.loc['A':'B', 'column1':'column2']

column1  column2
A        6        5
B        1        8

# df[     ]

In [76]:
df

column1  column2  column3
A        6        5        1
B        1        8        7
C        1        5        4

In [78]:
df[['column1']] # Kullanabilirsin

column1
A        6
B        1
C        1

In [87]:
df[['column1', 'column3']] # Kullanabilirsin.

column1  column3
A        6        1
B        1        7
C        1        4

In [100]:
df['A':'B'] # Bunu kullanma!

column1  column2  column3
A        6        5        1
B        1        8        7
C        1        5        4

df[   ] içine satır ifadelerini kullanma sadece sütunlara erişmek için kullan ama slice metodunuda kullanma. Slice metodunu kullanmak veya satırlara erişmek için .loc[] veya .iloc[] metodlarını kullan!

**___________________________________________________________________________________________________________**

In [103]:
df

column1  column2  column3
A        6        5        1
B        1        8        7
C        1        5        4

In [105]:
df.loc[:, 'column1':'column2']

column1  column2
A        6        5
B        1        8
C        1        5

In [106]:
df.loc['A':'B']

column1  column2  column3
A        6        5        1
B        1        8        7

In [107]:
df.loc['A':'B', 'column1':'column2']

column1  column2
A        6        5
B        1        8

In [108]:
df.iloc[0:2, 0:2]

column1  column2
A        6        5
B        1        8

**________________________________________________________________________________________________________**

In [109]:
df

column1  column2  column3
A        6        5        1
B        1        8        7
C        1        5        4

In [111]:
df['column3'][df['column3'] > 5]

B    7
Name: column3, dtype: int32

In [112]:
df

column1  column2  column3
A        6        5        1
B        1        8        7
C        1        5        4

In [120]:
df[df.column3 > 3]

column1  column2  column3
B        1        8        7
C        1        5        4