# Array Birleştirme (Concatenation)

In [1]:
import numpy as np

In [2]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])

In [4]:
np.concatenate([x, y])

array([1, 2, 3, 4, 5, 6])

**Arrayleri '.concatenate' metodu ile birleştirdik.**

In [5]:
z = np.array([7, 8, 9])

In [6]:
np.concatenate([x, y, z])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

istediğimiz kadar array birleştirebiliriz.

In [7]:
# iki boyut

In [8]:
a = np.array([[1, 2, 3],
              [4, 5, 6]])


In [13]:
np.concatenate([a, a]) # ' axis ' argümanın ön tanımlı değeri 0' dır. 

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

' **axis=0** ' ile **İndexler' i birleştirme** işlemi yapabiliriz.

In [12]:
np.concatenate([a, a], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

' **axis=1** ' ile **Columnlar' ı birleştirme** işlemi yapabiliriz.