# Array Ayırma (Splitting)

In [5]:
import numpy as np

**TEK BOYUTLU ARRAYLERİ AYIRMA**

In [6]:
x = np.array([1, 2, 3, 99, 99, 3, 2, 1])

In [7]:
a,b,c = np.split(x, [3, 5]) # köşeli parantez içinde verilen index değerleri arrayin bölüneceği noktaları belirtir.

Tek boyuttaki arraylari bölmek için '.split' metodunu kullanabiliriz.

In [8]:
a

array([1, 2, 3])

In [9]:
b

array([99, 99])

In [10]:
c

array([3, 2, 1])

**İKİ BOYUTLU ARRAYLERİ AYIRMA**

In [11]:
m = np.arange(16).reshape(4, 4)

Tek boyutlu bir array oluşturup yeniden boyutlandırdık.

In [12]:
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [13]:
ust,alt = np.vsplit(m, [2]) # **Vertical Split**

**___________________________________________________________**

In [14]:
ust

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [15]:
alt

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [16]:
sag, sol = np.hsplit(m, [2]) # **Horizantal Split**

In [17]:
sag

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [18]:
sol

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])